[package]
name = "bin"
version = "0.1.0"
edition = "2021"

[dependencies]
ariadne = "0.2.0"
chumsky = "1.0.0-alpha.3"
clap = { version = "4.2.4", features = ["derive"] }
syntax = { path = "../syntax" }
typing = { path = "../typing" }
