[package]
name = "entry"
version = "0.1.0"
edition = "2021"

[dependencies]
parser = { path = "../parser" }
lower = { path = "../lower" }
compiler = { path = "../compiler" }
vm = { path = "../vm" }

[[bin]]
name = "hmc"
path = "src/main.rs"